---
- name: Create Text File on Linux and Windows using AWX
  hosts: all

  tasks:
    - name: Set remote temporary directory
      win_shell: |
        $env:TMPDIR = "C:\temp"
      delegate_to: localhost
      
    - name: Create a text file on Linux
      shell: echo "Hello World!" > ~/kekw.txt
      when: "'192.168.1.123' in inventory_hostname"

    - name: Create a text file on Windows
      win_shell: echo "Hello World!" > C:\Users\Administrator\kekw.txt
      when: "'192.168.1.138' in inventory_hostname"
