---
- name: Create Text File on Windows using AWX
  hosts: all  # Replace with the name of your Windows host defined in AWX inventory

  tasks:
    - name: Create a text file
      shell: echo "Hello World!" > kekw.txt 
