---
- name: Create Text File on Linux and Windows using AWX
  hosts: all
  vars:
    ansible_remote_tmp: 'C:/Users/Administrator/AppData/Local/Temp/ansible'

  tasks:
    - name: Create a text file on Linux
      shell: echo "Hello World!" > ~/kekw.txt
      when: "'192.168.1.123' in inventory_hostname"

    - name: Create a text file on Windows
      win_shell: echo "Hello World!" > C:\Users\Administrator\kekw.txt
      when: "'192.168.1.138' in inventory_hostname"
